# Data Cleaning – Superstore Sales Dataset

## Purpose
This notebook applies the necessary transformations identified
during the data profiling phase to prepare the dataset for analysis.

1️⃣ Import libraries

In [1]:
import pandas as pd

2️⃣ Load dataset

In [3]:
df_raw = pd.read_csv("../data/raw/superstore_raw.csv")
df = df_raw.copy()

3️⃣ Dataset Overview Before Cleaning

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

5️⃣ Convert Date Columns

Order Date and Ship Date were stored as object type.

They will be converted to datetime format to enable time-based analysis.

In [6]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d/%m/%Y")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d/%m/%Y")

6️⃣ Handle Missing Postal Codes

Only 11 records contain missing values in the Postal Code column.
Given the low percentage, records will be retained and missing
values will be labeled as "Unknown" to preserve dataset integrity.

In [7]:
df["Postal Code"] = df["Postal Code"].fillna("Unknown")

7️⃣ Standardize Data Types


Postal Code will be converted to string format to prevent
misinterpretation as a numerical variable.

In [13]:
df["Postal Code"] = df["Postal Code"].astype(str)
df["Postal Code"] = df["Postal Code"].str.replace(".0", "", regex=False)

8️⃣ Final Dataset Check

In [17]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   datetime64[ns]
 3   Ship Date      9800 non-null   datetime64[ns]
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9800 non-null   object
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: datetime64[ns](2), float64(1), int64(1), object(14)
memory usage: 1.3+ MB

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

9️⃣ Cleaning Summary

The dataset was cleaned according to the findings from the
data profiling phase.

Actions performed:

- Converted date columns to datetime format
- Handled missing Postal Codes
- Standardized data types

The dataset is now structurally consistent and ready for
exploratory data analysis.

🔟 Basic Feature Engineering - Shipping Lead Time

A new feature will be created to measure the number of days
between Order Date and Ship Date.

This metric is relevant for operational efficiency analysis
and service-level evaluation.

In [ ]:
df["Lead Time (Days)"] = (df["Ship Date"] - df["Order Date"]).dt.days
df["Lead Time (Days)"].describe()

count    9800.000000
mean        3.961122
std         1.749614
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Lead Time (Days), dtype: float64

In [23]:
# Check for negative lead times
df[df["Lead Time (Days)"] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Lead Time (Days)]
Index: []

1️⃣1️⃣ Basic Featute Engineering - Year / Month

Year and Month features are created to facilitate
trend analysis and time-series aggregation.

In [24]:
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month
df["Order Month Name"] = df["Order Date"].dt.month_name()

# For Power BI, we can also create a "Year-Month" column
df["Order Year-Month"] = df["Order Date"].dt.to_period("M").astype(str)

In [25]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Lead Time (Days),Order Year,Order Month,Order Month Name,Order Year-Month
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3,2017,11,November,2017-11
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,2017,11,November,2017-11
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,2017,6,June,2017-06
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7,2016,10,October,2016-10
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7,2016,10,October,2016-10

1️⃣2️⃣ Order-Level Consistency Check

Since an Order ID can contain multiple products,
key attributes such as Order Date, Customer ID,
and Ship Mode should remain consistent within each order.

In [30]:
order_consistency = df.groupby("Order ID").agg(
    {
        "Order Date": "nunique",
        "Customer ID": "nunique",
        "Ship Mode": "nunique",
    }
)

order_consistency[
    (order_consistency["Order Date"] > 1) | (order_consistency["Customer ID"] > 1) | (order_consistency["Ship Mode"] > 1)
]

Empty DataFrame
Columns: [Order Date, Customer ID, Ship Mode]
Index: []

1️⃣3️⃣ Enhanced Data Preparation Summary

In addition to structural cleaning, feature engineering
was applied to enhance analytical capability.

New features created:

- Shipping Lead Time
- Order Year / Month
- Year-Month aggregation key
- Order-level consistency validation

The dataset is now analytics-ready and structured
for both business intelligence and operational insights.

In [35]:
# Save cleaned data
df.to_csv("../data/processed/superstore_cleaned.csv", index=False)